export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'

export const USE_EN = 'USE_EN'
export const USE_ZH = 'USE_ZH'

export const GET_USER_INFO = 'GET_USER_INFO'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'

export const RELEASE_ARTICLE = 'RELEASE_ARTICLE'
export const GET_BLOG_LIST = 'GET_ARTICLE_LIST'
export const GET_BLOG_INFO = 'GET_ARTICLE_INFO'

export const REGISTER_SUCCESS_TRUE = 'REGISTER_SUCCESS_TRUE'
export const REGISTER_SUCCESS_FALSE = 'REGISTER_SUCCESS_FALSE'

export const GET_TODAY_RECOMMEND = 'GET_TODAY_RECOMMEND'

export const INPUT_MARKDOWN = 'INPUT_MARKDOWN'
export const EDIT_TAG = 'EDIT_TAG'

export const SEND_VERIFY_EMAIL_SUCCESS = 'SEND_VERIFY_EMAIL_SUCCESS'
