export const GET_USER_INFO = 'GET_USER_INFO'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'

export const RELEASE_ARTICLE = 'RELEASE_ARTICLE'
export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST'
export const GET_ARTICLE_INFO = 'GET_ARTICLE_INFO'

export const SHOW_NAV_MENU = 'SHOW_NAV_MENU'
export const HIDE_NAV_MENU = 'HIDE_NAV_MENU'

export const REGISTER_SUCCESS_TRUE = 'REGISTER_SUCCESS_TRUE'
export const REGISTER_SUCCESS_FALSE = 'REGISTER_SUCCESS_FALSE'