import {
 GET_BADGE_NUM,
  GET_BLOG_INFO,
  GET_BLOG_LIST,
  GET_TODAY_RECOMMEND,
  GET_USER_INFO,
  INPUT_MARKDOWN,
  LOGIN,
  LOGOUT,
  REGISTER_SUCCESS_FALSE,
  REGISTER_SUCCESS_TRUE,
} from './action-types'


